// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MergeNow
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidMergeNowPackageString = "0741861b-9c7e-4aad-a1d2-04379f0caa44";
        public static Guid guidMergeNowPackage = new Guid(guidMergeNowPackageString);

        public const string guidViewTfsHistoryString = "ffe1131c-8ea1-4d05-9728-34ad4611bda9";
        public static Guid guidViewTfsHistory = new Guid(guidViewTfsHistoryString);

        public const string guidMergeNowPackageCmdString = "0665ed10-e211-4f58-ac69-3d9ec6291e4e";
        public static Guid guidMergeNowPackageCmd = new Guid(guidMergeNowPackageCmdString);

        public const string guidImagesString = "b3b7c397-2fce-4cdf-8518-f2c5647b6b84";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int ViewTfsHistoryId = 0x1040;
        public const int MergeNowMenuGroup = 0x1875;
        public const int MergeNowCommandId = 0x1876;
        public const int mergeNowPic = 0x0001;
    }
}