// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MergeNow
{
    internal sealed partial class Vsix
    {
        public const string Id = "MergeNow.d8f14fa9-4942-4d3f-99e3-a5d1b85d8e41";
        public const string Name = "MergeNow";
        public const string Description = @"Visual Studio 2022 extension for making quick TFVC merges. Pick a changeset and merge it directly to selected target branch.";
        public const string Language = "en-US";
        public const string Version = "4.0";
        public const string Author = "Kamil Wachala";
        public const string Tags = "tfs; tfvs; visual studio; extension; changeset; merge";
    }
}
